age = input("Введите возраст пользователя:")
print(age)
pol = input("Введите пол пользователя :")
print(pol)
name = input("Введите имя пользователя:")
print(name)
city = input("Введите город пользователя:")
print(city)
clas = input(" Введите в каком классе пользователь учится:")
print(clas)